apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-13--1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "pwn-101"
  template:
    metadata:
      labels:
        app: "pwn-101"
    spec:
      containers:
      - name: "pwn-base"
        image: "kind/challenge/pwn-base:a44d686fa8f46944928878c0164deb29ce1300ce2199e989118e8e984aa21cf5"
        env: []
        ports:
        - containerPort: 1200
