services:
  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - API_URL_CONTROLSERVER=${API_URL_CONTROLSERVER}
      - API_URL_ADMINSERVER=${API_URL_ADMINSERVER}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - HOST_CACHE=${HOST_CACHE}
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379  # Sử dụng tên service `cache`
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
      - cache
    networks:
      - default

  # nginx:
  #   image: nginx:stable
  #   restart: always
  #   volumes:
  #     - ./conf/nginx/http.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - ctfd
  #   networks:
  #     - default

  db:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - default
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    ports:
      - "6379:6379"  # Mở cổng để truy cập từ local
    restart: always
    volumes:
      - .data/redis:/data
    networks:
      - default

networks:
  default:
    driver: bridge  # Sử dụng bridge network mặc định của Docker Compose