apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-77--1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "pwn-101"
  template:
    metadata:
      labels:
        app: "pwn-101"
    spec:
      containers:
      - name: "pwn-base"
        image: "kind/challenge/pwn-base:ad787749b1f981299f9dc478bed2b8bd8b28b958c062aa00bf797d3344904960"
        env: []
        ports:
        - containerPort: 1200
