apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-14-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "file-exploit"
  template:
    metadata:
      labels:
        app: "file-exploit"
    spec:
      containers:
      - name: "web-base"
        image: "kind/challenge/web-base:ce0796a7a88658c71c48d376a292ddc371526c7080ca9ae17a086962fabfb0f9"
        env: []
        ports:
        - containerPort: 80
