apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-6-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "websecchallenge"
  template:
    metadata:
      labels:
        app: "websecchallenge"
    spec:
      containers:
      - name: "web-base"
        image: "kind/challenge/web-base:f28c1d9200faada29ec1ce5a6c7348f341f25fc12a3259eaf22c599ba924acba"
        env: []
        ports:
        - containerPort: 80
