apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsproblem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wsproblem
  template:
    metadata:
      labels:
        app: wsproblem
    spec:
      containers:
        - name: web-base
          image:
          ports:
            - containerPort: 80 