apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-104-59"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "pwn-101"
  template:
    metadata:
      labels:
        app: "pwn-101"
    spec:
      containers:
      - name: "pwn-base"
        image: "kind/challenge/pwn-base:ef3a66b316783e1b5e75d088f3f9b379e48f601c623f3cdbe78373e09b7a7eef"
        env: []
        ports:
        - containerPort: 1200
