apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-99-50"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "pwn-challenge"
  template:
    metadata:
      labels:
        app: "pwn-challenge"
    spec:
      containers:
      - name: "pwn-base"
        image: "kind/challenge/pwn-base:7c2681500f221db71e538f3a15691349e7bdfc67d103bbb811840a42a2cf1442"
        env: []
        ports:
        - containerPort: 8012
