apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-102-50"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "my-app"
  template:
    metadata:
      labels:
        app: "my-app"
    spec:
      containers:
      - name: "web"
        image: "kind/challenge/web:e8cb1d0d8b6a3001b98edf77dcb08c38d26d5bc3bd6fb84b2280644741e772aa"
        env:
        - name: "FLASK_ENV"
          value: "development"
        - name: "MYSQL_HOST"
          value: "127.0.0.1"
        - name: "MYSQL_DATABASE"
          value: "mydatabase"
        - name: "MYSQL_USER"
          value: "myuser"
        - name: "MYSQL_PASSWORD"
          value: "123"
        ports:
        - containerPort: 5000
      - name: "db"
        image: "kind/challenge/db:3ab07cc5f3e4bba1863f39ad97669e1af1a2b2cc697624c478b5f80c85650761"
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "123"
        - name: "MYSQL_DATABASE"
          value: "mydatabase"
        ports:
        - containerPort: 3306
