apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-98-50"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "websecchallenge"
  template:
    metadata:
      labels:
        app: "websecchallenge"
    spec:
      containers:
      - name: "web-base"
        image: "kind/challenge/web-base:663302192599f00a766db7bba5c6efbbaffaee646a0e0fb8d299cabd89ef84dc"
        env: []
        ports:
        - containerPort: 80
