apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-105-89"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "wsproblem"
  template:
    metadata:
      labels:
        app: "wsproblem"
    spec:
      containers:
      - name: "web-base"
        image: "kind/challenge/web-base:2d3ce4882e0b4e02b973e41cf53e3df2db1e54c6a7c2bc8b7e6a0c3971bc2999"
        env: []
        ports:
        - containerPort: 80
