apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-100-50"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "file-exploit"
  template:
    metadata:
      labels:
        app: "file-exploit"
    spec:
      containers:
      - name: "web-base"
        image: "kind/challenge/web-base:802c35d36119c1c977d4bbb13bce8156d21a7c09188c095b3978da5a93981865"
        env: []
        ports:
        - containerPort: 80
