apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-12-5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "websecchallenge"
  template:
    metadata:
      labels:
        app: "websecchallenge"
    spec:
      containers:
      - name: "web-base"
        image: "kind/challenge/web-base:71892caf00ba85281d4464ec7a72c75d8751bffb2b5d80bba043cc69a4e0fa9d"
        env: []
        ports:
        - containerPort: 80
