apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-101-50"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "the_mindfullness_inside"
  template:
    metadata:
      labels:
        app: "the_mindfullness_inside"
    spec:
      containers:
      - name: "web-base"
        image: "kind/challenge/web-base:89744cf56e568d1d24695d10fe706f0d10cce7afb234c632c7cfbf2ff8cf3edd"
        env: []
        ports:
        - containerPort: 8000
      - name: "db-base"
        image: "kind/challenge/db-base:b1d7cf7b5360eec728aff8b364b90cbb5239be6342dcd2e266d5e73e4c837b62"
        env:
        - name: "POSTGRES_DB"
          value: "postgres"
        - name: "POSTGRES_USER"
          value: "postgres"
        - name: "POSTGRES_PASSWORD"
          value: "postgres"
        ports:
        - containerPort: 5432
